# -*- coding: utf-8 -*-
"""assignment_2_a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19g0SpJgGcL6RXr2x2GNvpOj49rP2J81x
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma'],
    'Employee ID': [101, 102, 103, 104, 105],
    'Age': [30, 35, 28, 40, 32],
    'Salary': [50000, 60000, 45000, 70000, 55000],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing']
}

df = pd.DataFrame(data)

# Display the initial dataset
print("Initial Dataset:")
print(df)
print()

# Data cleaning process
# Handling missing values
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Display the cleaned dataset
print("Cleaned Dataset:")
print(df)
print()

# Visualize the Growth of each employee using bar chart
plt.figure(figsize=(10, 6))
plt.bar(df['Name'], df['Salary'], color='red')
plt.xlabel('Employee Name')
plt.ylabel('Salary')
plt.title('Salary Growth of Employees')
plt.xticks(rotation=45)
plt.show()